apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  template:
    spec:
      containers:
        - name: quarkus
          envFrom:
            - configMapRef:
                name: db-config
